# Generated by Django 3.1.6 on 2022-06-15 11:15

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='static/developers_cv', validators=[account.validators.Validators.validate_file_extension]),
        ),
    ]
