# Generated by Django 3.1.6 on 2022-06-15 11:16

import account.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20220615_1116'),
        ('account', '0002_auto_20220615_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applied_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='static/developers_cv', validators=[account.validators.Validators.validate_file_extension]),
        ),
    ]
