# Generated by Django 4.0.5 on 2022-06-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('modification_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='account')),
                ('status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('finished', 'finished')], default='open', max_length=20)),
                ('user_marked_done', models.BooleanField(default=False)),
                ('creator_marked_done', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='tag.tag')),
            ],
        ),
    ]
