# Generated by Django 4.0.5 on 2022-06-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_accepted_dev_job_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='accepted_dev',
        ),
    ]
