# Generated by Django 4.0.5 on 2022-06-15 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0004_remove_job_accepted_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accepted_dev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_dev', to=settings.AUTH_USER_MODEL),
        ),
    ]
